<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.offeringprotocol</groupId>
    <artifactId>odp-java</artifactId>
    <version>0.1.1</version>
  </parent>

  <artifactId>odp-agent</artifactId>
  <name>ODP Agent</name>
  <description>Agent-oriented Service discovery and catalog navigation for ODP.</description>

  <properties>
    <automatic.module.name>org.offeringprotocol.odp.agent</automatic.module.name>
  </properties>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>odp-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>odp-directory</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
